### ISSUE TITLE
module spams errors in mm log

### ISSUE THREAD

**Issue by motey** [mrVragec/MMM-mvgmunich#36]
Hi,
thanks for the module. great Work! 
It works for me on the surface, but.. :)
I have configured two stations like this:
```js
 modules: [{
                module: "mvgmunich",
                position: "bottom_left",
                header: "Harras",
                config: {
                        haltestelle: "Harras",
                        maxEntries: 10, // 10 items on screen
                        updateInterval: 30000, // 30 s
                        showIcons: true, // Show transport type icon
                        transportTypesToShow: {
                                "ubahn": true, // show ubahn route
                                "sbahn": true, // show sbahn route
                                "bus": false, // show bus route
                                "tram": false // show tram route
                        },
                        ignoreStations: [], // destination not to be shown
                        timeToWalk: 10, // 10 min walking time to station. Default is 0
                        showWalkingTime: true, // if the walking time should be included and the starting time is displayed
                        showTrainDepartureTime: true, // show tran departure time
                        trainDepartureTimeFormat: "relative", // format of the train departure time
                        walkingTimeFormat: "relative", // format of the walking time
                }
        },
        {
                module: "mvgmunich",
                position: "bottom_right",
                header: "Johann-Clanze-Straße",
                config: {
                        haltestelle: "Johann-Clanze-Straße",
                        maxEntries: 10, // 10 items on screen
                        updateInterval: 30000, // 30 s
                        showIcons: true, // Show transport type icon
                        transportTypesToShow: {
                                "ubahn": false, // show ubahn route
                                "sbahn": false, // show sbahn route
                                "bus": true, // show bus route
                                "tram": false // show tram route
                        },
                        ignoreStations: [], // destination not to be shown
                        timeToWalk: 5, // 10 min walking time to station. Default is 0
                        showWalkingTime: true, // if the walking time should be included and the starting time is displayed
                        showTrainDepartureTime: true, // show tran departure time
                        trainDepartureTimeFormat: "relative", // format of the train departure time
                        walkingTimeFormat: "relative", // format of the walking time
                }
        }]
```

This results in tons of the same error in the log
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/mvgmunich/node_helper.js:56:27)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/mvgmunich/node_helper.js:56:27)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
```
Maybe it makes sense to create a catch here or to fix the issue.
Thanks for any help

**Comment by mrVragec** [comment]
Ho @motey, 

I just fix something similar in this branch 'showing_2_stations'. Would be possible to check it if it's working for you? 
I will try to create a new version asap I will get confirmation that this is working also for someone else not only for me and on my computer.

**Comment by motey** [comment]
that was quick :)
looks good at first glance. Will leave it running until tomorow and give you another feedback.
cheers

**Comment by motey** [comment]
Still got some errors in the log (definitive less errors), but this time in combination with an out of memory error. will investigate if its maybe node.js + raspi issue. maybe its not the modules fault.

**Comment by mrVragec** [comment]
@motey would be possible to past errors here if they are related to this module?

**Comment by motey** [comment]
@mrVragec Maybe, did not found the time yesterday to investigate. will do the next days

**Comment by motey** [comment]
Could not pinpoint the memoryleak yet, but assuming that this is the cause for my issues. Closing this issue for now. Thanks for the help and the module in general :heart:
