### ISSUE TITLE
No data or incomplete data is displayed

### ISSUE THREAD

**Issue by charraeus** [mrVragec/MMM-mvgmunich#45]
No data or incomplete data is displayed.
Enclosed is the error log from  ~/.pm2/logs/

> [2020-10-04 23:09:49.553] [ERROR]  Error while parsing and sending departure info SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Request._callback (/home/pi/MagicMirror/modules/mvgmunich/node_helper.js:59:31)
>     at Request.self.callback (/home/pi/MagicMirror/modules/mvgmunich/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:200:13)
>     at Request.<anonymous> (/home/pi/MagicMirror/modules/mvgmunich/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:200:13)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/mvgmunich/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:288:20)
>     at IncomingMessage.emit (events.js:205:15)
>     at endReadableNT (_stream_readable.js:1154:12)
> [2020-10-05 10:15:39.514] [ERROR]  Error while parsing and sending departure info SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at Request._callback (/home/pi/MagicMirror/modules/mvgmunich/node_helper.js:59:31)
>     at Request.self.callback (/home/pi/MagicMirror/modules/mvgmunich/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:200:13)
>     at Request.<anonymous> (/home/pi/MagicMirror/modules/mvgmunich/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:200:13)
>     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/mvgmunich/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:288:20)
>     at IncomingMessage.emit (events.js:205:15)
>     at endReadableNT (_stream_readable.js:1154:12)
> 

This is my config:
 ```
               {
                        module: "mvgmunich",
                        disabled: false,
                        position: "bottom_right",
                        header: "MVG",
                        config: {
                                haltestelle: "Putzbrunn, Michael-Haslbeck-Straße",
                                //haltestelle: "Karlsplatz",
                                maxEntries: 5,              // 5 items on screen
                                updateInterval: 60000,      // 60 s
                                transportTypesToShow: {
                                        "ubahn": true,            // show ubahn route
                                        "sbahn": true,            // show sbahn route
                                        "bus": true,              // show bus route
                                        "regional_bus": true,     // show regional bus route
                                        "tram": true              // show tram route
                                },
                                ignoreStations: ["Neubiberg, Unterbiberg", "Grasbrunn, Kirchplatz"],         // destination not to be shown
                                timeToWalk: 2,             // min walking time to station. Default is 0
                                showWalkingTime: false,   // if the walking time should be included and the starting time is displayed
                                showTrainDepartureTime: true, // if the time of train departure should be displayed
                                trainDepartureTimeFormat: "absolute", // time format: absolute: 21:10; relative: in 8 min
                                 walkingTimeFormat: "relative", // time format: absolute: 21:08; relative: in 6 min
                                 showInterruptions: true,
                                 showInterruptionsDetails: true,
                                 countInterruptionsAsItemShown: false,
                                 lineFiltering: {
                                                "active": false,                        // set this to active if filtering should be used
                                                "filterType": "whitelist",              
                                                "lineNumbers": ["U1", "U3", "X50"]      // lines that should be on the w
                                  }
                        }
                },

```

**Comment by charraeus** [comment]
Tested yesterday again:

Haltestelle --> Result
\-----------------------
* "Putzbrunn, Michael-Haslbeck-Straße"  -->  No data or incomplete data
* "Putzbrunn, M.-Haslbeck-Straße"           --> "Michael-Haslbeck-Strasse" and "undefined", sometimes only Bus 212 (Bus 55 Data missing
* "Michael-Haslbeck-Straße"                      --> "Michael-Haslbeck-Strasse" with complete Data (Busses 212 and 55)

**Comment by mrVragec** [comment]
@charraeus I just tested configuration from your first post, and for me some how everything works correctly. I can see 5 items on the screen. 

Would be possible to check some logs?

**Comment by mrVragec** [comment]
Closing as no activity on it.
